const engineUtil = (function () {
  const providerMap = { 
    "address": faker.address.streetAddress, 
    "boolean": "", 
    "buildingNumber": "", 
    "bs": "", 
    "catchPhrase": "", 
    "century": "", 
    "chrome": "", 
    "city": faker.address.city,
    "cityPrefix": faker.address.cityPrefix, 
    "citySuffix": faker.address.citySuffix, 
    "colorName": "", 
    "company": "", 
    "companyEmail": "", 
    "companySuffix": "", 
    "county": faker.address.county, 
    "country": faker.address.country, 
    "countryCode": faker.address.countryCode,
    "department": faker.commerce.department,
    "productName": faker.commerce.productName,
    "price": faker.commerce.price,
    "productAdjective": faker.commerce.productAdjective,
    "productMaterial": faker.commerce.productMaterial,
    "product": faker.commerce.product,
    "productName": faker.commerce.productName,
    "expirationDate": "", 
    "full": "", 
    "number": "", 
    "provider": "", 
    "securityCode": "",
    "cryptoCode": "",
    "currencyCode": "", 
    "date": "",
    "dateTime": "", 
    "dateTimeThisDecade": "", 
    "dateTimeThisMonth": "", 
    "dateTimeThisYear": "", 
    "dayOfMonth": "", 
    "dayOfWeek": "", 
    "domainName": "", 
    "domainWord": "", 
    "ean13": "", 
    "ean8": "", 
    "email": "", 
    "fileExtension": "", 
    "fileName": "", 
    "filePath": "", 
    "firefox": "", 
    "firstName": "", 
    "firstNameFemale": "", 
    "firstNameMale": "", 
    "freeEmail": "", 
    "freeEmailDomain": "", 
    "name": "", 
    "fullNameFemale": "", 
    "nameMale": "", 
    "futureDate": "", 
    "futureDateTime": "", 
    "hexColor": "", 
    "imageUrl": "", 
    "internetExplorer": "", 
    "ipv4": "", 
    "ipv6": "", 
    "isbn10": "", 
    "isbn13": "", 
    "iso8601": "", 
    "languageCode": "", 
    "lastName": "", 
    "latitude": faker.address.latitude, 
    "licensePlate": "", 
    "linuxPlatformToken": "", 
    "locale": "", 
    "longitude": faker.address.longitude, 
    "macAddress": "", 
    "macPlatformToken": "", 
    "md5": "", 
    "militaryAPO": "", 
    "militaryDPO": "", 
    "militaryShip": "", 
    "militaryState": "", 
    "mimeType": "", 
    "month": "", 
    "monthName": "", 
    "nullBoolean": "", 
    "opera": "", 
    "paragraph": "", 
    "password": "", 
    "pastDate": "", 
    "pastDateTime": "", 
    "phoneNumber": "", 
    "postCode": "", 
    "postalCode": "", 
    "postalCodePlus4": "", 
    "prefix": "",
    "prefixFemale": "", 
    "randomDigit": "", 
    "randomLetter": "", 
    "rgbColor": "",
    "rgbCssColor": "", 
    "safari": "", 
    "safeColorName": "", 
    "safeEmail": "", 
    "safeHexColor": "", 
    "secondaryAddress": faker.address.secondaryAddress,
    "sentence": "", 
    "sha1": "", 
    "sha256": "", 
    "slug": "", 
    "ssn": "", 
    "state": faker.address.state, 
    "stateAbbr": faker.address.stateAbbr, 
    "streetAddress": "", 
    "streetName": faker.address.streetName, 
    "streetSuffix": faker.address.streetSuffix, 
    "streetPrefix": faker.address.streetPrefix, 
    "suffix": "", 
    "time": "", 
    "timeDelta": "", 
    "timeZone": "", 
    "tld": "", 
    "unixTime": "", 
    "uri": "", 
    "uriExtension": "", 
    "uriPage": "", 
    "uriPath": "", 
    "url": "", 
    "userAgent": "", 
    "userName": "", 
    "uuid4": "", 
    "windowsPlatformToken": "", 
    "word": "", 
    "year": "", 
    "zipCode": faker.address.zipCode() 
  }

  return {
    outputMessage: (message) => {
      Alteryx.Engine.SendMessage.Info(message);
    },
    shouldGiveLowQualityValue: (probabilityOfLowQualityData) => {
      return false
    },
    getGeneratedValueFromProvider: (provider) => {
      engineUtil.outputMessage('Provider: ' + provider)
      return providerMap[provider]() //TODO Enable passing of params
    }
  }
}())

